apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-serv-deployment
spec:
  selector:
    matchLabels:
      app: car-serv
  replicas: 1
  template:
    metadata:
      labels:
        app: car-serv
    spec:
      containers:
        - name: car-serv
          image: elroydevops/car-serv
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: car-serv-service
spec:
  type: NodePort
  selector:
    app: car-serv
  ports:
    - protocol: TCP
      nodePort: 30099
      port: 80
      targetPort: 80
