apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template: # bat dau tu day de dinh nghia mot pod
    metadata:
      labels: # thic dat bn lable cx dc (va tuy ten)
        app: nginx
        service_name: service_a
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
